### ISSUE TITLE
disable email to users after granting access

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/ckanext-restricted#1]
@genkimaps I don't seem to have permission to push to this repo, so I made a new branch on the server, made some changes, tested, and merged back with master. 

The reason for this change is that if a dataset has multiple resources, the user gets a flurry of emails (1 for each resource and it's overkill). The email requests still works where the user requests access to a restricted resource.

Seems to work fine now.

**Comment by genkimaps** [comment]
@cole-fields You should have access now.  I understand why this was done, and the change should be ok.  I don't see any potential side effects at this point.

**Comment by cole-fields** [comment]
@genkimaps perfect, thanks
